# .goreleaser.yml file
# dank-mcp - another AgentDank joint
# Copyright (c) 2025 Neomantra Corp
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: dank-mcp

before:
  hooks:
    - go mod tidy

builds:
  - main: main.go
    id: dank-mcp
    binary: dank-mcp
    ldflags:
      - -s -w -X github.com/AgentDank/dank-mcp/internal/version.Version={{.Version}}
    goarch:
      # duckdb-go only supports these
      - amd64
      - arm64
    goos:
      - linux
      - darwin
      - windows
    ignore:
      # duckdb-go does not support these
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - dank-mcp
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
        entitlements: ./etc/entitlements.plist
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 20m

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

universal_binaries:
  - replace: true

release:
  github:
    owner: AgentDank
    name: dank-mcp

brews:
  - homepage: https://github.com/AgentDank/dank-mcp
    description: "AgentDank MCP Server"
    directory: Formula
    repository:
      owner: AgentDank
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@neomantra.net
    install: |
      bin.install "dank-mcp"
